import type { Metadata } from 'next'
import localFont from 'next/font/local'
import React from 'react'

import './globals.css'
import { ThemeProvider } from '@/provider/ThemeProvider'

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
})

const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
})

export const metadata: Metadata = {
	title: 'Marshal Blog',
	description: 'Generated by Blogger',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${geistSans.className} ${geistMono.className}`}>
				<ThemeProvider
					attribute='class'
					defaultTheme='system'
					enableSystem
					disableTransitionOnChange
				>
					{children}
				</ThemeProvider>{' '}
			</body>
		</html>
	)
}
